services:
  postgres:
    container_name: postgres-spotify
    image: postgres
    environment:
      POSTGRES_USER: codecake
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: codecake
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
    driver: local